### ISSUE TITLE
VS 2017 incompatible

### ISSUE THREAD

**Issue by ron194** [pumasecurity/puma-scan#23]
VS 2017 incompatible

**Comment by ejohn20** [comment]
Looks like VS 2017 official release is early March. Once released, this will be added to the roadmap.

**Comment by CFlatWouldbeMinor** [comment]
I would really like to have this addon supported by VS2017 as it is now officially available as RTM

**Comment by ejohn20** [comment]
I'll pick this off soon. I just need to actually upgrade to 2017 and update the installer. At least, in theory that is.

**Comment by CFlatWouldbeMinor** [comment]
I just did a clone.I have registered for contribution.I may try to contribute in this topcRegards Ruedi
-------- Ursprüngliche Nachricht --------Von: Eric Johnson <notifications@github.com> Datum: 29.03.17  17:27  (GMT+01:00) An: pumasecurity/puma-scan <puma-scan@noreply.github.com> Cc: RuediG <ruedi.gabriel@gmail.com>, Comment <comment@noreply.github.com> Betreff: Re: [pumasecurity/puma-scan] VS 2017 incompatible (#23) 
I'll pick this off soon. I just need to actually upgrade to 2017 and update the installer. At least, in theory that is.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pumasecurity/puma-scan","title":"pumasecurity/puma-scan","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pumasecurity/puma-scan"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ejohn20 in #23: I'll pick this off soon. I just need to actually upgrade to 2017 and update the installer. At least, in theory that is."}],"action":{"name":"View Issue","url":"https://github.com/pumasecurity/puma-scan/issues/23#issuecomment-290126542"}}}

**Comment by ejohn20** [comment]
That works also. Did you happen to try installing via the nuget pakcage to see if that works in 2017?

**Comment by CFlatWouldbeMinor** [comment]
Yes I tried, but it does not work.
I hope there is just the need for a small change

**Comment by ejohn20** [comment]
Just commited this to the master branch. I've tested the extension and nuget package in both 2015 and 2017. Everything seems to be working well.

**Comment by ejohn20** [comment]
Visual Studio 2017 support has been released in 1.0.5 to nuget and the marketplace.
