### ISSUE TITLE
jwt AuthorizeAttribute ignored

### ISSUE THREAD

**Issue by rlgordey** [pumasecurity/puma-scan#70]
I use jwt Tokens in my Asp.Net Core API. I have a custom AuthorizeAttribute that I have marked my controllers with. How do I tell puma-scan that this is equivalent to the Microsoft AuthorizeAttribute? I have a ton of SEC0120 in my error list.

**Comment by meadisu27** [comment]
Puma Scan Community Edition does not provide a way to ignore custom implementations. However, you are welcome to fork and modify the code to look for your custom authorize attribute. Otherwise, Puma Scan Professional Edition may be a good candidate for you as it allows for custom configuration of suppressions, taints, cleanse methods, sinks, etc.
